### ISSUE TITLE
TODO list of ideas for tutorials

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXTutorials#2]
- [x] [Piano app](https://www.youtube.com/watch?v=4AVgeN202jw)
- [ ] A game similar to hangman where letters are replaced by numbers, e.g. A = 1, B = 2, etc
- [ ] Ludo game
- [x] [Tower of Hanoi](https://www.youtube.com/watch?v=nCdKCDSMUeA)
- [ ] Print with graphics, text, print preview, multipage split
- [ ] Kotlin introduction
- [x] [Polynomial function vis](https://www.youtube.com/watch?v=TO-18dw6EOw)
- [x] [Dialogs API](https://www.youtube.com/watch?v=vrEnmDZW7Ag)
- [x] Java - C++ communication via JNI
- [ ] Image editor: zoom, lasso, transparency
- [ ] ControlsFX
- [ ] JavaFX 3d maze game - FXGL - FXyz
- [ ] Jpro web example
- [x] [JavaFX custom bindings / properties](https://www.youtube.com/watch?v=mOLkdt2sGjA)
- [x] [client plugin - javafx on android](https://www.youtube.com/watch?v=Gc-Mn4MO-zA)
- [x] [compression](https://youtu.be/-e_TQ7L3ock)
- [ ] Canvas vs PixelBuffer
- [ ] Pros and cons: JavaFX vs other GUIs 
- [x] Hide images inside images
- [ ] Live editor: two windows, one edits code, the other has live visualisation / drawing

**Comment by 87fahim** [comment]
Please do the Ludo game. I did wrote some code but I could put the pieces together to finish the game. I have problem with animation of this Ludo game.

**Comment by legymhueck** [comment]
As I have suggested the Towers of Hanoi game, I would very much like to see that.
In Germany, the Towers of Hanoi are part of upper sixth form introduction to recursion.
I think I've already succeeded in making my students like JavaFX (over AWT or SWING) which long-standing teachers and professors are reluctant to adopt.
There are some really ugly GUIs that I have to use, e.g. for displaying tree structures [example](https://www.google.de/imgres?imgurl=x-raw-image%3A%2F%2F%2F61322f829b3033fb7fd030cdf4ca18e1a6fced39a833b3721b283b6350658eb3&imgrefurl=http%3A%2F%2Farchiv.goethe-gymnasium-dortmund.de%2Fprojekte%2FInfoHomepage%2FInformatik%2FDynStr2019-generisch.pdf&tbnid=-zMwm4IvMmF65M&vet=12ahUKEwiHqpKGx4PpAhVM16QKHeRECFgQMyg9egUIARCAAQ..i&docid=e1golfNrcx_SuM&w=450&h=259&q=bin%C3%A4rbaum%20java%20nrw%20informatik&ved=2ahUKEwiHqpKGx4PpAhVM16QKHeRECFgQMyg9egUIARCAAQ)

Thanks for the awesome projects!

**Comment by AlmasB** [comment]
@legymhueck this is now completed. Please see link above
